spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gulimall_pms?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

#可以通过设置spring:main:allow-circular-references为true。
#不鼓励使用循环引用，默认情况下是禁止使用的。更新应用程序以删除bean之间的依赖循环。
#作为最后的手段
  main:
    allow-circular-references: true

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10000

#swagger
swagger:
  groupname: gulimall-product-pro
  title: gulimall-product-pro

