spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gulimall_pms?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

#不鼓励使用循环引用,默认情况下是禁止使用的,更新应用程序以删除bean之间的依赖循环。
  main:
    allow-circular-references: true
#解决Swagger documentationPluginsBootstrapper  npe异常
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10000

knife4j:
  # 开启生产环境屏蔽
  production: true
swagger:
  module:
    name: ProductModel
# 关闭烦人的提示信息
logging:
  level:
    springfox:
      documentation:
        spring:
          web:
            readers:
              operation:
                CachingOperationNameGenerator: warn

#apollo配置中心
app:
  id: zero10001

apollo:
  meta: http://106.54.227.205:8080
  bootstrap:
    enabled: true
    namespaces: application