spring:
  cloud:
    gateway:
      routes:

        - id: product_route
          uri: lb://mall-pro-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        ## 前端项目，/api
        ## http://localhost:88/api/captcha.jpg   http://localhost:8080/renren-fast/captcha.jpg
        ## http://localhost:88/api/product/category/list/tree http://localhost:10000/product/category/list/tree


        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}


        - id: member_route
          uri: lb://mall-pro-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}


        - id: ware_route
          uri: lb://mall-pro-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}


        - id: admin_route
          uri: lb://renren-fast-pro
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}



##enabled：默认为false,设置为true表明spring cloud gateway开启服务发现和路由的功能,
##网关自动根据注册中心的服务名为每个服务创建一个router,将以服务名开头的请求路径转发到对应的服务
#      discovery:
#        locator:
#          enabled: true
##lowerCaseServiceId：启动 locator.enabled=true 自动路由时，路由的路径默认会使用大写ID，若想要使用小写ID，可将lowerCaseServiceId设置为true
#          lower-case-service-id: true

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: mall-pro-gateway

server:
  port: 88
