server:
  port: 8080

spring:
  application:
    name: camunda-application

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/camunda?serverTimezone=GMT%2B8
    username: root
    password: 123456
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
  #解决Swagger documentationPluginsBootstrapper  npe异常
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jersey:
    application-path: /engine-rest

#更改Camunda的日志级别
logging:
  level:
    org.camunda.bpm.engine.impl.persistence.entity: debug
    #关闭swagger2烦人的提示信息
    springfox:
      documentation:
        spring:
          web:
            readers:
              operation:
                CachingOperationNameGenerator: warn

camunda:
  bpm:
    admin-user:
      id: camunda
      password: admin
      first-name: admin

    database:
      type: mysql

    filter:
      create: All tasks

    #配置路径
    webapp:
      application-path: /mycamunda
      #禁用
      index-redirect-enabled: true

    #Camunda默认不开启序列化,开启序列化
    generic-properties:
      properties:
        javaSerializationFormatEnabled: true

    #开启camunda的权限管理
    authorization:
      enabled: true

    #关闭自动部署
    auto-deployment-enabled: false
