server:
  port: 8080

spring:
  application:
    name: camunda-application

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/camunda?serverTimezone=GMT%2B8
    username: root
    password: 123456


logging:
  level:
#    org.camunda.bpm.engine*: debug
#    //org.camunda.bpm.engine.impl.persistence.entity
    org.camunda.bpm.engine.impl.persistence.entity: debug

camunda:
  bpm:
    admin-user:
      id: camunda
      password: admin
      first-name: admin
    filter:
      create: All tasks
#    配置路径
    webapp:
      application-path: /mycamunda
