server:
  port: 8080

spring:
  application:
    name: camunda-application
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/camunda?serverTimezone=GMT%2B8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#解决Swagger documentationPluginsBootstrapper  npe异常
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jersey:
    application-path: /engine-rest
#Camunda
logging:
  level:
    org.camunda.bpm.engine.impl.persistence.entity: debug

#关闭swagger2烦人的提示信息
    springfox:
      documentation:
        spring:
          web:
            readers:
              operation:
                CachingOperationNameGenerator: warn

swagger:
  module:
    name: ProcessMoudel

camunda:
  bpm:
    admin-user:
      id: camunda
      password: admin
      first-name: admin
#如果希望允许对 restapi 发出跨源请求，则需要启用 CORS。
#    run:
#      cors:
#        enable: true
#        allowed-origins: "*"
#      auth:
#        enable: true
#        authentication: basic
    database:
      type: mysql
    filter:
      create: All tasks
    #配置路径
    webapp:
      application-path: /mycamunda
    #禁用
      index-redirect-enabled: false
    #Camunda默认不开启序列化,开启序列化
    generic-properties:
      properties:
        javaSerializationFormatEnabled: true

#knife4j:
## 开启生产环境屏蔽
#  production: true



